{% set version = "0.15.0" %}

package:
  name: tensorflow-hub
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/hub.git
  git_rev: v{{ version }}

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  
requirements:
  build:
    - {{ compiler('c') }}       # [ppc_arch != "p10"]
    - {{ compiler('cxx') }}     # [ppc_arch != "p10"]
    - bazel {{ bazel }}
  host:
    - git >=2.2
    - python  # noarch package; don't tie to specific python version
    - ml_dtypes {{ ml_dtypes }}
  run:
    - python  # noarch package; don't tie to specific python version
    - numpy {{ numpy }}
    - protobuf {{ protobuf }}
    - tensorflow-base {{ tensorflow }}
    - tensorflow-estimator {{ tf_estimator }}
    - ml_dtypes {{ ml_dtypes }}

test:
  imports:
    - tensorflow
    - tensorflow_hub

about:
  home: https://www.tensorflow.org/hub/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ SRC_DIR }}/tensorflow_hub/LICENSE
  summary: "A library for transfer learning by reusing parts of TensorFlow models."
  description: |
    TensorFlow Hub is a repository of reusable assets for machine learning 
    with TensorFlow. In particular, it provides pre-trained SavedModels that 
    can be reused to solve new tasks with less training time and less training data.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
